apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        resources:
          limits:
            memory: "500Mi"
            cpu: "0.5"
          requests:
            memory: "200Mi"
            cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec: 
  selector:
    app: rabbitmq
  type: NodePort
  ports: 
  - port: 15672
    name: rabbitmgt
  - port: 5672
    name: rabbit